name: CI/CD

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-2"
          SOURCE_DIR: "public"

  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Get SHA7
        id: vars
        run: echo "::set-output name=SHA7::$(git rev-parse --short HEAD)"

      - name: Build docker image
        run: docker build --tag darrylforbes/hyacinth-nginx:${{ steps.vars.outputs.SHA7 }} .

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push darrylforbes/hyacinth-nginx:${{ steps.vars.outputs.SHA7 }}

  push:
    needs: build

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Get SHA7
        id: vars
        run: echo "::set-output name=SHA7::$(git rev-parse --short HEAD)"

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull docker image
        run: docker pull darrylforbes/hyacinth-nginx:${{ steps.vars.outputs.SHA7 }}

      - name: Tag image
        run: docker tag darrylforbes/hyacinth-nginx:${{ steps.vars.outputs.SHA7 }} darrylforbes/hyacinth-nginx:latest

      - name: Push image
        run: docker push darrylforbes/hyacinth-nginx:latest
